/* ==========================================================================
 * Morphy CLI — Transition Catalog
 * AUTO-GENERATED by scripts/sync.ts — do not edit manually.
 * ========================================================================== */

export interface TransitionMeta {
  name: string;
  displayName: string;
  description: string;
  category: string;
  fileName: string;
}

export const CATEGORY_EMOJI: Record<string, string> = {
  'flow': '🌊',
  'portal': '🌀',
  'paper': '📄',
  'mask': '🎭',
  'spatial': '🧊',
  'dynamic': '⚡',
  'experimental': '🧪',
};

export const CATEGORY_LABELS: Record<string, string> = {
  'dynamic': 'Dynamic',
  'experimental': 'Experimental',
  'flow': 'Flow',
  'mask': 'Mask',
  'paper': 'Paper',
  'portal': 'Portal',
  'spatial': 'Spatial',
};

export const TRANSITIONS: TransitionMeta[] = [
  {
    name: 'slash',
    displayName: 'Slash',
    description: 'A sharp diagonal cut slices into the next page.',
    category: 'dynamic',
    fileName: 'slash.tsx',
  },
  {
    name: 'bounce',
    displayName: 'Bounce',
    description: 'Dynamic bounce transition',
    category: 'experimental',
    fileName: 'bounce.tsx',
  },
  {
    name: 'dissolve',
    displayName: 'Dissolve',
    description: 'Dynamic dissolve transition',
    category: 'experimental',
    fileName: 'dissolve.tsx',
  },
  {
    name: 'flip',
    displayName: 'Flip',
    description: 'Dynamic flip transition',
    category: 'experimental',
    fileName: 'flip.tsx',
  },
  {
    name: 'fold',
    displayName: 'Fold',
    description: 'Dynamic fold transition',
    category: 'experimental',
    fileName: 'fold.tsx',
  },
  {
    name: 'ghost',
    displayName: 'Ghost',
    description: 'Dynamic ghost transition',
    category: 'experimental',
    fileName: 'ghost.tsx',
  },
  {
    name: 'glass',
    displayName: 'Glass',
    description: 'Dynamic glass transition',
    category: 'experimental',
    fileName: 'glass.tsx',
  },
  {
    name: 'glitch',
    displayName: 'Glitch',
    description: 'Dynamic glitch transition',
    category: 'experimental',
    fileName: 'glitch.tsx',
  },
  {
    name: 'liquid-morph',
    displayName: 'Liquid Morph',
    description: 'Pages melt and reshape into each other like liquid.',
    category: 'experimental',
    fileName: 'liquid-morph.tsx',
  },
  {
    name: 'mirror',
    displayName: 'Mirror',
    description: 'Dynamic mirror transition',
    category: 'experimental',
    fileName: 'mirror.tsx',
  },
  {
    name: 'neon',
    displayName: 'Neon',
    description: 'Dynamic neon transition',
    category: 'experimental',
    fileName: 'neon.tsx',
  },
  {
    name: 'pixel',
    displayName: 'Pixel',
    description: 'Dynamic pixel transition',
    category: 'experimental',
    fileName: 'pixel.tsx',
  },
  {
    name: 'ripple',
    displayName: 'Ripple',
    description: 'Dynamic ripple transition',
    category: 'experimental',
    fileName: 'ripple.tsx',
  },
  {
    name: 'shadow',
    displayName: 'Shadow',
    description: 'Dynamic shadow transition',
    category: 'experimental',
    fileName: 'shadow.tsx',
  },
  {
    name: 'spin',
    displayName: 'Spin',
    description: 'Dynamic spin transition',
    category: 'experimental',
    fileName: 'spin.tsx',
  },
  {
    name: 'squeeze',
    displayName: 'Squeeze',
    description: 'Dynamic squeeze transition',
    category: 'experimental',
    fileName: 'squeeze.tsx',
  },
  {
    name: 'stretch',
    displayName: 'Stretch',
    description: 'Dynamic stretch transition',
    category: 'experimental',
    fileName: 'stretch.tsx',
  },
  {
    name: 'swipe',
    displayName: 'Swipe',
    description: 'Dynamic swipe transition',
    category: 'experimental',
    fileName: 'swipe.tsx',
  },
  {
    name: 'tv-turn-off',
    displayName: 'CRT TV Turn Off',
    description: 'Emulates an old CRT television collapsing into a horizontal line and fading out.',
    category: 'experimental',
    fileName: 'tv-turn-off.tsx',
  },
  {
    name: 'vortex',
    displayName: 'Vortex',
    description: 'Dynamic vortex transition',
    category: 'experimental',
    fileName: 'vortex.tsx',
  },
  {
    name: 'wave',
    displayName: 'Wave',
    description: 'Dynamic wave transition',
    category: 'experimental',
    fileName: 'wave.tsx',
  },
  {
    name: 'wobble',
    displayName: 'Wobble',
    description: 'Dynamic wobble transition',
    category: 'experimental',
    fileName: 'wobble.tsx',
  },
  {
    name: 'zoom',
    displayName: 'Zoom',
    description: 'Dynamic zoom transition',
    category: 'experimental',
    fileName: 'zoom.tsx',
  },
  {
    name: 'fade',
    displayName: 'Fade',
    description: 'Smooth opacity transition',
    category: 'flow',
    fileName: 'fade.tsx',
  },
  {
    name: 'scale',
    displayName: 'Scale',
    description: 'A zoom-in/zoom-out transition with opacity.',
    category: 'flow',
    fileName: 'scale.tsx',
  },
  {
    name: 'slide',
    displayName: 'Slide',
    description: 'A directional slide transition between pages.',
    category: 'flow',
    fileName: 'slide.tsx',
  },
  {
    name: 'ink-spread',
    displayName: 'Ink Spread',
    description: 'Ink spreads organically across the screen revealing the next scene.',
    category: 'mask',
    fileName: 'ink-spread.tsx',
  },
  {
    name: 'origami-unfold',
    displayName: 'Origami Unfold',
    description: 'A 3D paper folding and unfolding effect.',
    category: 'paper',
    fileName: 'origami-unfold.tsx',
  },
  {
    name: 'page-curl',
    displayName: 'Page Curl',
    description: 'A realistic page curl effect using CSS 3D transforms. No WebGL required.',
    category: 'paper',
    fileName: 'page-curl.tsx',
  },
  {
    name: 'circular-portal',
    displayName: 'Circular Portal',
    description: 'A circular mask reveal that expands from a point to reveal the new page.',
    category: 'portal',
    fileName: 'circular-portal.tsx',
  },
  {
    name: 'shutter-iris',
    displayName: 'Camera Shutter',
    description: 'A cinematic camera shutter iris effect closing and opening.',
    category: 'portal',
    fileName: 'shutter-iris.tsx',
  },
  {
    name: 'wormhole',
    displayName: 'Wormhole',
    description: 'Space bends and stretches as the page transforms into another world.',
    category: 'portal',
    fileName: 'wormhole.tsx',
  },
  {
    name: 'cube',
    displayName: 'Cube',
    description: 'Pages rotate like faces of a 3D cube.',
    category: 'spatial',
    fileName: 'cube.tsx',
  },
];

export const TRANSITION_NAMES = TRANSITIONS.map((t) => t.name);

export function getTransitionsByCategory(): Map<string, TransitionMeta[]> {
  const map = new Map<string, TransitionMeta[]>();
  for (const t of TRANSITIONS) {
    const list = map.get(t.category) ?? [];
    list.push(t);
    map.set(t.category, list);
  }
  return map;
}
