/* ==========================================================================
 * Morphy CLI — Sync Script
 * Copies frontend/components/morphy → cli/templates/
 * Extracts transition metadata → cli/src/data/transitions.ts
 * ========================================================================== */

import fs from 'fs';
import path from 'path';

const ROOT = path.resolve(import.meta.dirname, '..');
const FRONTEND_MORPHY = path.resolve(ROOT, '..', 'frontend', 'components', 'morphy');
const TEMPLATES_DIR = path.resolve(ROOT, 'templates');
const DATA_OUTPUT = path.resolve(ROOT, 'src', 'data', 'transitions.ts');

// ---------------------------------------------------------------------------
// 1. Copy all source files into templates/
// ---------------------------------------------------------------------------

function copyRecursive(src: string, dest: string) {
  if (!fs.existsSync(src)) {
    console.error(`❌ Source not found: ${src}`);
    process.exit(1);
  }

  if (fs.existsSync(dest)) {
    fs.rmSync(dest, { recursive: true, force: true });
  }
  fs.mkdirSync(dest, { recursive: true });

  const entries = fs.readdirSync(src, { withFileTypes: true });
  for (const entry of entries) {
    const srcPath = path.join(src, entry.name);
    const destPath = path.join(dest, entry.name);

    if (entry.isDirectory()) {
      copyRecursive(srcPath, destPath);
    } else {
      fs.copyFileSync(srcPath, destPath);
    }
  }
}

// ---------------------------------------------------------------------------
// 2. Extract transition metadata from .tsx files
// ---------------------------------------------------------------------------

interface TransitionMeta {
  name: string;
  displayName: string;
  description: string;
  category: string;
  fileName: string;
}

function extractTransitionMeta(filePath: string, fileName: string): TransitionMeta | null {
  const content = fs.readFileSync(filePath, 'utf-8');

  // Extract name
  const nameMatch = content.match(/name:\s*['"]([^'"]+)['"]/);
  if (!nameMatch) return null;

  // Extract displayName
  const displayNameMatch = content.match(/displayName:\s*['"]([^'"]+)['"]/);

  // Extract description (handle multi-line)
  const descMatch = content.match(/description:\s*(?:['"]([^'"]+)['"]|[^,]+['"]([^'"]+)['"])/);

  // Extract category
  const categoryMatch = content.match(/category:\s*['"]([^'"]+)['"]/);

  return {
    name: nameMatch[1],
    displayName: displayNameMatch?.[1] ?? nameMatch[1],
    description: descMatch?.[1] ?? descMatch?.[2] ?? '',
    category: categoryMatch?.[1] ?? 'flow',
    fileName,
  };
}

function scanTransitions(): TransitionMeta[] {
  const transitionsDir = path.join(FRONTEND_MORPHY, 'transitions');
  if (!fs.existsSync(transitionsDir)) {
    console.error('❌ Transitions directory not found');
    process.exit(1);
  }

  const files = fs.readdirSync(transitionsDir).filter((f) => f.endsWith('.tsx'));
  const metas: TransitionMeta[] = [];

  for (const file of files) {
    const meta = extractTransitionMeta(path.join(transitionsDir, file), file);
    if (meta) {
      metas.push(meta);
    } else {
      console.warn(`⚠️  Could not extract metadata from ${file}`);
    }
  }

  // Sort by category then name
  metas.sort((a, b) => a.category.localeCompare(b.category) || a.name.localeCompare(b.name));

  return metas;
}

// ---------------------------------------------------------------------------
// 3. Generate src/data/transitions.ts
// ---------------------------------------------------------------------------

function generateCatalog(metas: TransitionMeta[]): string {
  const categoryEmoji: Record<string, string> = {
    flow: '🌊',
    portal: '🌀',
    paper: '📄',
    mask: '🎭',
    spatial: '🧊',
    dynamic: '⚡',
    experimental: '🧪',
  };

  const lines = [
    '/* ==========================================================================',
    ' * Morphy CLI — Transition Catalog',
    ' * AUTO-GENERATED by scripts/sync.ts — do not edit manually.',
    ' * ========================================================================== */',
    '',
    'export interface TransitionMeta {',
    '  name: string;',
    '  displayName: string;',
    '  description: string;',
    '  category: string;',
    '  fileName: string;',
    '}',
    '',
    'export const CATEGORY_EMOJI: Record<string, string> = {',
  ];

  for (const [cat, emoji] of Object.entries(categoryEmoji)) {
    lines.push(`  '${cat}': '${emoji}',`);
  }
  lines.push('};');
  lines.push('');

  // Category labels
  lines.push('export const CATEGORY_LABELS: Record<string, string> = {');
  const categories = [...new Set(metas.map((m) => m.category))];
  for (const cat of categories) {
    const label = cat.charAt(0).toUpperCase() + cat.slice(1);
    lines.push(`  '${cat}': '${label}',`);
  }
  lines.push('};');
  lines.push('');

  lines.push(`export const TRANSITIONS: TransitionMeta[] = [`);
  for (const meta of metas) {
    lines.push(`  {`);
    lines.push(`    name: '${meta.name}',`);
    lines.push(`    displayName: '${meta.displayName}',`);
    lines.push(`    description: '${meta.description.replace(/'/g, "\\'")}',`);
    lines.push(`    category: '${meta.category}',`);
    lines.push(`    fileName: '${meta.fileName}',`);
    lines.push(`  },`);
  }
  lines.push('];');
  lines.push('');

  lines.push(`export const TRANSITION_NAMES = TRANSITIONS.map((t) => t.name);`);
  lines.push('');

  lines.push(`export function getTransitionsByCategory(): Map<string, TransitionMeta[]> {`);
  lines.push(`  const map = new Map<string, TransitionMeta[]>();`);
  lines.push(`  for (const t of TRANSITIONS) {`);
  lines.push(`    const list = map.get(t.category) ?? [];`);
  lines.push(`    list.push(t);`);
  lines.push(`    map.set(t.category, list);`);
  lines.push(`  }`);
  lines.push(`  return map;`);
  lines.push(`}`);
  lines.push('');

  return lines.join('\n');
}

// ---------------------------------------------------------------------------
// Main
// ---------------------------------------------------------------------------

console.log('');
console.log('🔄 Morphy CLI Sync');
console.log('─'.repeat(50));
console.log('');

// Step 1: Copy templates
console.log('📦 Copying frontend/components/morphy → cli/templates/');
copyRecursive(FRONTEND_MORPHY, TEMPLATES_DIR);
console.log('   ✅ Templates synced');
console.log('');

// Step 2: Extract metadata
console.log('🔍 Scanning transition metadata...');
const metas = scanTransitions();
console.log(`   Found ${metas.length} transitions`);
console.log('');

// Step 3: Generate catalog
console.log('📝 Generating src/data/transitions.ts...');
const catalog = generateCatalog(metas);
const dataDir = path.dirname(DATA_OUTPUT);
if (!fs.existsSync(dataDir)) {
  fs.mkdirSync(dataDir, { recursive: true });
}
fs.writeFileSync(DATA_OUTPUT, catalog, 'utf-8');
console.log('   ✅ Catalog generated');
console.log('');

// Summary
const categories = [...new Set(metas.map((m) => m.category))];
console.log('📊 Summary:');
for (const cat of categories) {
  const count = metas.filter((m) => m.category === cat).length;
  console.log(`   ${cat}: ${count} transitions`);
}
console.log('');
console.log('✨ Sync complete!');
console.log('');
