/* ==========================================================================
 * GlideCN — Transition Catalog
 * The single source of truth for ALL transition metadata used across the
 * documentation site: sidebar, gallery, showcase pages, and overview cards.
 *
 * To add a new transition to the docs, add an entry here. Everything else
 * (sidebar, gallery, doc pages) auto-syncs from this file.
 * ========================================================================== */

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

export interface TransitionMetrics {
  /** Target FPS (always 60 for GPU-accelerated) */
  fps: number;
  /** Approximate gzipped bundle contribution in KB */
  bundleSize: string;
  /** Complexity: 'Low' | 'Medium' | 'High' */
  complexity: 'Low' | 'Medium' | 'High';
}

export interface TransitionCatalogEntry {
  /** Machine-readable slug (must match the registry name) */
  slug: string;
  /** Human-friendly display name */
  displayName: string;
  /** One-liner tagline */
  description: string;
  /** Extended description for the showcase page */
  longDescription: string;
  /** Grouping category (matches TransitionCategory type) */
  category: 'flow' | 'portal' | 'paper' | 'mask' | 'spatial' | 'dynamic' | 'experimental';
  /** Family group name for sidebar/gallery */
  family: string;
  /** Playful emoji icon */
  emoji: string;
  /** Whether this appears in the "Featured" sidebar section */
  featured: boolean;
  /** Performance & size metrics */
  metrics: TransitionMetrics;
  /** Ideal use-case descriptions */
  useCases: string[];
  /** What makes this transition special — shown as a highlight */
  whySpecial: string;
  /** Short tags for "Best for" pills */
  bestFor: string[];
  /** Feature flags — what the transition provides */
  features: string[];
  /** Implementation status */
  status?: 'done' | 'coming-soon';
}

// ---------------------------------------------------------------------------
// Catalog Data
// ---------------------------------------------------------------------------

export const TRANSITION_CATALOG: TransitionCatalogEntry[] = [
  // ── Flow ────────────────────────────────────────────────────────────────
  {
    slug: 'fade',
    displayName: 'Fade',
    description: 'Smooth opacity transition',
    longDescription:
      'The most universal transition — a clean opacity crossfade that works everywhere. It\'s the default for a reason: fast, elegant, and never distracting. Perfect as a baseline or when content should speak for itself.',
    category: 'flow',
    family: 'Flow',
    emoji: '',
    featured: false,
    metrics: { fps: 60, bundleSize: '~0.3kb', complexity: 'Low' },
    useCases: [
      'Default page transitions',
      'Content-heavy pages where the transition shouldn\'t distract',
      'Loading state handoffs',
    ],
    whySpecial: 'GPU-accelerated opacity animation. Zero layout recalculation, zero jank. The fastest transition in the library.',
    bestFor: ['Landing pages', 'Blogs', 'Dashboards', 'Any page'],
    features: ['GPU-accelerated', 'SSR-safe', 'Reduced-motion aware', 'Zero layout shift'],
    status: 'done',
  },
  {
    slug: 'slide',
    displayName: 'Slide',
    description: 'A directional slide transition between pages',
    longDescription:
      'Classic directional movement that creates a natural spatial relationship between pages. Slide left to advance, right to go back — users intuitively understand the navigation hierarchy.',
    category: 'flow',
    family: 'Flow',
    emoji: '➡️',
    featured: false,
    metrics: { fps: 60, bundleSize: '~0.5kb', complexity: 'Low' },
    useCases: [
      'Multi-step wizards and onboarding flows',
      'Tab-based navigation',
      'Forward/backward navigation patterns',
    ],
    whySpecial: 'Four directional variants (left, right, up, down) from one definition. Automatically pairs entry/exit for spatial consistency.',
    bestFor: ['Wizards', 'Onboarding', 'Tabs', 'Navigation'],
    features: ['GPU-accelerated', 'SSR-safe', 'Reduced-motion aware', '4 directions', 'Auto-paired exit'],
    status: 'done',
  },
  {
    slug: 'scale',
    displayName: 'Scale',
    description: 'A zoom-in/zoom-out transition with opacity',
    longDescription:
      'A cinematic zoom that makes content feel like it\'s emerging from or receding into the screen. Configurable scale-from and scale-to values let you dial in the exact intensity.',
    category: 'flow',
    family: 'Flow',
    emoji: '',
    featured: false,
    metrics: { fps: 60, bundleSize: '~0.4kb', complexity: 'Low' },
    useCases: [
      'Hero reveals and product spotlights',
      'Modal-like page transitions',
      'Focus and detail views',
    ],
    whySpecial: 'Customizable entry and exit scale values. The zoom-in/zoom-out feel adds depth without complexity.',
    bestFor: ['Product pages', 'Modals', 'Detail views', 'Galleries'],
    features: ['GPU-accelerated', 'SSR-safe', 'Reduced-motion aware', 'Configurable scale range'],
    status: 'done',
  },

  // ── Portal ──────────────────────────────────────────────────────────────
  {
    slug: 'circular-portal',
    displayName: 'Circular Portal',
    description: 'A circular mask reveal expanding from a configurable origin',
    longDescription:
      'A dramatic circular clip-path reveal that expands outward from any point you choose. It feels like opening a portal to the next page — cinematic, attention-grabbing, and endlessly configurable.',
    category: 'portal',
    family: 'Portal',
    emoji: '',
    featured: false,
    metrics: { fps: 60, bundleSize: '~0.6kb', complexity: 'Medium' },
    useCases: [
      'Click-origin reveals (button → page)',
      'Hero section transitions',
      'Interactive storytelling moments',
    ],
    whySpecial: 'Configurable origin point — the circle can expand from a button click, center, or any coordinates you specify.',
    bestFor: ['Interactive sites', 'Storytelling', 'Click reveals', 'Hero sections'],
    features: ['GPU-accelerated', 'SSR-safe', 'Reduced-motion aware', 'Custom origin point', 'Clip-path based'],
    status: 'done',
  },
  {
    slug: 'wormhole',
    displayName: 'Wormhole',
    description: 'Space bends and stretches as the page transforms',
    longDescription:
      'The most dramatic transition in the library. Pages scale, rotate, and blur simultaneously, creating a sense of warping through dimensions. Use sparingly for maximum impact.',
    category: 'portal',
    family: 'Portal',
    emoji: '🕳️',
    featured: false,
    metrics: { fps: 60, bundleSize: '~0.5kb', complexity: 'Medium' },
    useCases: [
      'Special reveals and surprise moments',
      'Game-like interfaces',
      'Experimental creative projects',
    ],
    whySpecial: 'Combines scale, rotation, and blur in a single choreographed sequence for an otherworldly transition effect.',
    bestFor: ['Creative sites', 'Games', 'Experimental UI', 'Special moments'],
    features: ['GPU-accelerated', 'SSR-safe', 'Reduced-motion aware', 'Multi-axis animation', 'Blur effect'],
    status: 'done',
  },

  // ── Paper ───────────────────────────────────────────────────────────────
  {
    slug: 'page-curl',
    displayName: 'Page Curl',
    description: 'A realistic page curl effect using CSS 3D transforms',
    longDescription:
      'Simulates the physical act of turning a page using pure CSS 3D transforms — no WebGL required. The curl direction and perspective are fully configurable, creating a tactile, book-like experience.',
    category: 'paper',
    family: 'Paper',
    emoji: '',
    featured: false,
    metrics: { fps: 60, bundleSize: '~0.7kb', complexity: 'Medium' },
    useCases: [
      'E-book and reader interfaces',
      'Portfolio and lookbook pages',
      'Editorial and magazine layouts',
    ],
    whySpecial: 'Pure CSS 3D transforms with realistic shadow casting. No WebGL, no canvas — just Framer Motion orchestrating CSS.',
    bestFor: ['E-books', 'Portfolios', 'Magazines', 'Editorial'],
    features: ['GPU-accelerated', 'SSR-safe', 'Reduced-motion aware', 'CSS 3D transforms', 'No WebGL', 'Configurable curl direction'],
    status: 'done',
  },

  // ── Mask ────────────────────────────────────────────────────────────────
  {
    slug: 'ink-spread',
    displayName: 'Ink Spread',
    description: 'Ink spreads organically across the screen revealing the next scene',
    longDescription:
      'An organic, artistic reveal where a clip-path circle expands with a dramatic brightness/contrast burst — like ink dropping on paper and spreading outward. High visual impact.',
    category: 'mask',
    family: 'Mask',
    emoji: '🖋️',
    featured: false,
    metrics: { fps: 60, bundleSize: '~0.5kb', complexity: 'Medium' },
    useCases: [
      'Art and design portfolios',
      'Creative agency websites',
      'Section reveals with impact',
    ],
    whySpecial: 'Combines clip-path animation with brightness/contrast filters for an ink-on-paper effect that\'s purely CSS-driven.',
    bestFor: ['Art sites', 'Portfolios', 'Creative agencies', 'Impact moments'],
    features: ['GPU-accelerated', 'SSR-safe', 'Reduced-motion aware', 'Clip-path based', 'Filter effects'],
    status: 'done',
  },

  // ── Spatial ─────────────────────────────────────────────────────────────
  {
    slug: 'cube',
    displayName: 'Cube',
    description: 'Pages rotate like faces of a 3D cube',
    longDescription:
      'Pages are treated as faces of a 3D cube that rotates to reveal the next view. The perspective and rotation axis adapt to the configured direction, giving a genuine 3D spatial feel.',
    category: 'spatial',
    family: 'Spatial',
    emoji: '',
    featured: false,
    metrics: { fps: 60, bundleSize: '~0.6kb', complexity: 'High' },
    useCases: [
      'Image galleries with spatial depth',
      'Product configurators',
      '3D-feeling navigation',
    ],
    whySpecial: 'True CSS 3D perspective with dynamic transform-origin calculation based on direction. Feels genuinely three-dimensional.',
    bestFor: ['Galleries', 'Product pages', '3D navigation', 'Presentations'],
    features: ['GPU-accelerated', 'SSR-safe', 'Reduced-motion aware', 'CSS 3D perspective', '4 directions', 'Dynamic transform-origin'],
    status: 'done',
  },

  // ── Dynamic ─────────────────────────────────────────────────────────────
  {
    slug: 'slash',
    displayName: 'Slash',
    description: 'A sharp diagonal cut slices into the next page',
    longDescription:
      'A bold, angular clip-path transition that slices diagonally across the viewport. The sharp geometry and aggressive easing create a dynamic, high-energy feel.',
    category: 'dynamic',
    family: 'Dynamic',
    emoji: '⚔️',
    featured: false,
    metrics: { fps: 60, bundleSize: '~0.4kb', complexity: 'Medium' },
    useCases: [
      'Action-oriented landing pages',
      'Sports and gaming interfaces',
      'Aggressive brand experiences',
    ],
    whySpecial: 'Polygon-based clip-path creates a true diagonal wipe — not a simple slide. The sharp easing curve amplifies the cutting feel.',
    bestFor: ['Action pages', 'Sports', 'Gaming', 'Bold brands'],
    features: ['GPU-accelerated', 'SSR-safe', 'Reduced-motion aware', 'Polygon clip-path', 'Sharp easing'],
    status: 'done',
  },

  // ── Experimental ────────────────────────────────────────────────────────
  {
    slug: 'liquid-morph',
    displayName: 'Liquid Morph',
    description: 'Pages melt and reshape into each other like liquid',
    longDescription:
      'An experimental transition where content blurs, scales, and drifts as if melting — then resolidifies as the new page. The combination of blur, scale, and y-translation creates a liquid, otherworldly feel.',
    category: 'experimental',
    family: 'Experimental',
    emoji: '',
    featured: true,
    metrics: { fps: 60, bundleSize: '~0.5kb', complexity: 'High' },
    useCases: [
      'Experimental art projects',
      'Interactive installations',
      'Creative portfolio pieces',
    ],
    whySpecial: 'Multi-property animation blending blur, scale, and translation for a truly liquid feel. Pushes CSS to its limits.',
    bestFor: ['Art projects', 'Installations', 'Creative portfolios', 'Experiments'],
    features: ['GPU-accelerated', 'SSR-safe', 'Reduced-motion aware', 'Multi-property blend', 'Blur effect', 'Experimental'],
    status: 'done',
  },
  {
    slug: 'tv-turn-off',
    displayName: 'CRT TV Off',
    description: 'An old television turning off and fading to black',
    longDescription: 'Simulates the effect of an old CRT TV collapsing horizontally then vertically and fading out to black. A very nostalgic, experimental transition effect.',
    category: 'experimental',
    family: 'Experimental',
    emoji: '',
    featured: false,
    metrics: { fps: 60, bundleSize: '~0.3kb', complexity: 'Low' },
    useCases: ['Retro websites', 'Special reveals', 'Video ending transitions'],
    whySpecial: 'Nostalgic scale deformation ending in a sharp brightness change to pure black.',
    bestFor: ['Retro designs', 'Portfolios', 'Creative sites'],
    features: ['GPU-accelerated', 'CSS filters', 'Scale deformation'],
    status: 'done',
  },
  {
    slug: 'shutter-iris',
    displayName: 'Shutter Iris',
    description: 'A cinematic camera shutter closing and opening',
    longDescription: 'A dramatic clip-path transition representing a camera shutter. The screen iris closes into a tight point and re-opens to reveal the next scene.',
    category: 'portal',
    family: 'Portal',
    emoji: '',
    featured: false,
    metrics: { fps: 60, bundleSize: '~0.4kb', complexity: 'Medium' },
    useCases: ['Photography portfolios', 'Cinematic reveals', 'Art direction pages'],
    whySpecial: 'Uses a complex 10-point polygon clip-path to simulate a mechanical shutter.',
    bestFor: ['Photography', 'Cinematic sites', 'Portfolios'],
    features: ['GPU-accelerated', 'Complex clip-path', 'Cinematic'],
    status: 'done',
  },
  {
    slug: 'origami-unfold',
    displayName: 'Origami Unfold',
    description: 'A 3D paper folding and unfolding effect',
    longDescription: 'Simulates the feeling of 3D origami paper unfolding using complex rotation and scale transforms. Gives the UI a very tangible, physical feeling.',
    category: 'paper',
    family: 'Paper',
    emoji: '',
    featured: false,
    metrics: { fps: 60, bundleSize: '~0.5kb', complexity: 'High' },
    useCases: ['Editorial sites', 'Digital menus', 'Creative interactions'],
    whySpecial: 'Combines X and Y 3D rotations with shifting transform origins to simulate unfolding paper.',
    bestFor: ['Editorial', 'Interactive storytelling', 'Creative sites'],
    features: ['GPU-accelerated', '3D rotation', 'Transform origins'],
    status: 'done',
  },
  {
    slug: 'glitch',
    displayName: 'Glitch',
    description: 'An amazing glitch transition effect',
    longDescription: 'A highly experimental, beautifully choreographed transition featuring glitch-inspired dynamics.',
    category: 'flow',
    family: 'Flow',
    emoji: '',
    featured: false,
    metrics: { fps: 60, bundleSize: '~0.0kb', complexity: 'Medium' },
    useCases: ['Creative interfaces', 'Special effects'],
    whySpecial: 'Highly experimental and fully GPU-accelerated.',
    bestFor: ['Creative interfaces', 'Special effects'],
    features: ['Creative interfaces', 'Special effects'],
    status: 'done',
  },
  {
    slug: 'pixel',
    displayName: 'Pixel Dissolve',
    description: 'An amazing pixel transition effect',
    longDescription: 'A highly experimental, beautifully choreographed transition featuring pixel-inspired dynamics.',
    category: 'portal',
    family: 'Portal',
    emoji: '',
    featured: true,
    metrics: { fps: 60, bundleSize: '~0.0kb', complexity: 'Medium' },
    useCases: ['Creative interfaces', 'Special effects'],
    whySpecial: 'Highly experimental and fully GPU-accelerated.',
    bestFor: ['Creative interfaces', 'Special effects'],
    features: ['Creative interfaces', 'Special effects'],
    status: 'done',
  },
  {
    slug: 'fold',
    displayName: 'Fold',
    description: 'An amazing fold transition effect',
    longDescription: 'A highly experimental, beautifully choreographed transition featuring fold-inspired dynamics.',
    category: 'paper',
    family: 'Paper',
    emoji: '',
    featured: false,
    metrics: { fps: 60, bundleSize: '~0.0kb', complexity: 'Medium' },
    useCases: ['Creative interfaces', 'Special effects'],
    whySpecial: 'Highly experimental and fully GPU-accelerated.',
    bestFor: ['Creative interfaces', 'Special effects'],
    features: ['Creative interfaces', 'Special effects'],
    status: 'done',
  },
  {
    slug: 'wave',
    displayName: 'Sine Wave',
    description: 'An amazing wave transition effect',
    longDescription: 'A highly experimental, beautifully choreographed transition featuring wave-inspired dynamics.',
    category: 'mask',
    family: 'Mask',
    emoji: '',
    featured: true,
    metrics: { fps: 60, bundleSize: '~0.0kb', complexity: 'Medium' },
    useCases: ['Creative interfaces', 'Special effects'],
    whySpecial: 'Highly experimental and fully GPU-accelerated.',
    bestFor: ['Creative interfaces', 'Special effects'],
    features: ['Creative interfaces', 'Special effects'],
    status: 'done',
  },
  {
    slug: 'shatter',
    displayName: 'Shatter',
    description: 'An amazing shatter transition effect',
    longDescription: 'A highly experimental, beautifully choreographed transition featuring shatter-inspired dynamics.',
    category: 'spatial',
    family: 'Spatial',
    emoji: '',
    featured: false,
    metrics: { fps: 60, bundleSize: '~0.0kb', complexity: 'Medium' },
    useCases: ['Creative interfaces', 'Special effects'],
    whySpecial: 'Highly experimental and fully GPU-accelerated.',
    bestFor: ['Creative interfaces', 'Special effects'],
    features: ['Creative interfaces', 'Special effects'],
    status: 'done',
  },
  {
    slug: 'dissolve',
    displayName: 'Dissolve',
    description: 'An amazing dissolve transition effect',
    longDescription: 'A highly experimental, beautifully choreographed transition featuring dissolve-inspired dynamics.',
    category: 'dynamic',
    family: 'Dynamic',
    emoji: '',
    featured: false,
    metrics: { fps: 60, bundleSize: '~0.0kb', complexity: 'Medium' },
    useCases: ['Creative interfaces', 'Special effects'],
    whySpecial: 'Highly experimental and fully GPU-accelerated.',
    bestFor: ['Creative interfaces', 'Special effects'],
    features: ['Creative interfaces', 'Special effects'],
    status: 'done',
  },
  {
    slug: 'swipe',
    displayName: 'Swipe',
    description: 'An amazing swipe transition effect',
    longDescription: 'A highly experimental, beautifully choreographed transition featuring swipe-inspired dynamics.',
    category: 'experimental',
    family: 'Experimental',
    emoji: '',
    featured: false,
    metrics: { fps: 60, bundleSize: '~0.0kb', complexity: 'Medium' },
    useCases: ['Creative interfaces', 'Special effects'],
    whySpecial: 'Highly experimental and fully GPU-accelerated.',
    bestFor: ['Creative interfaces', 'Special effects'],
    features: ['Creative interfaces', 'Special effects'],
    status: 'done',
  },
  {
    slug: 'flip',
    displayName: 'Flip',
    description: 'An amazing flip transition effect',
    longDescription: 'A highly experimental, beautifully choreographed transition featuring flip-inspired dynamics.',
    category: 'flow',
    family: 'Flow',
    emoji: '',
    featured: false,
    metrics: { fps: 60, bundleSize: '~0.0kb', complexity: 'Medium' },
    useCases: ['Creative interfaces', 'Special effects'],
    whySpecial: 'Highly experimental and fully GPU-accelerated.',
    bestFor: ['Creative interfaces', 'Special effects'],
    features: ['Creative interfaces', 'Special effects'],
    status: 'done',
  },
  {
    slug: 'spin',
    displayName: 'Spin',
    description: 'An amazing spin transition effect',
    longDescription: 'A highly experimental, beautifully choreographed transition featuring spin-inspired dynamics.',
    category: 'portal',
    family: 'Portal',
    emoji: '',
    featured: false,
    metrics: { fps: 60, bundleSize: '~0.0kb', complexity: 'Medium' },
    useCases: ['Creative interfaces', 'Special effects'],
    whySpecial: 'Highly experimental and fully GPU-accelerated.',
    bestFor: ['Creative interfaces', 'Special effects'],
    features: ['Creative interfaces', 'Special effects'],
    status: 'done',
  },
  {
    slug: 'zoom',
    displayName: 'Hyperspace Zoom',
    description: 'An amazing zoom transition effect',
    longDescription: 'A highly experimental, beautifully choreographed transition featuring zoom-inspired dynamics.',
    category: 'paper',
    family: 'Paper',
    emoji: '',
    featured: true,
    metrics: { fps: 60, bundleSize: '~0.0kb', complexity: 'Medium' },
    useCases: ['Creative interfaces', 'Special effects'],
    whySpecial: 'Highly experimental and fully GPU-accelerated.',
    bestFor: ['Creative interfaces', 'Special effects'],
    features: ['Creative interfaces', 'Special effects'],
    status: 'done',
  },
  {
    slug: 'bounce',
    displayName: 'Bounce',
    description: 'An amazing bounce transition effect',
    longDescription: 'A highly experimental, beautifully choreographed transition featuring bounce-inspired dynamics.',
    category: 'mask',
    family: 'Mask',
    emoji: '',
    featured: false,
    metrics: { fps: 60, bundleSize: '~0.0kb', complexity: 'Medium' },
    useCases: ['Creative interfaces', 'Special effects'],
    whySpecial: 'Highly experimental and fully GPU-accelerated.',
    bestFor: ['Creative interfaces', 'Special effects'],
    features: ['Creative interfaces', 'Special effects'],
    status: 'done',
  },
  {
    slug: 'wobble',
    displayName: 'Wobble',
    description: 'An amazing wobble transition effect',
    longDescription: 'A highly experimental, beautifully choreographed transition featuring wobble-inspired dynamics.',
    category: 'spatial',
    family: 'Spatial',
    emoji: '',
    featured: false,
    metrics: { fps: 60, bundleSize: '~0.0kb', complexity: 'Medium' },
    useCases: ['Creative interfaces', 'Special effects'],
    whySpecial: 'Highly experimental and fully GPU-accelerated.',
    bestFor: ['Creative interfaces', 'Special effects'],
    features: ['Creative interfaces', 'Special effects'],
    status: 'done',
  },
  {
    slug: 'stretch',
    displayName: 'Stretch',
    description: 'An amazing stretch transition effect',
    longDescription: 'A highly experimental, beautifully choreographed transition featuring stretch-inspired dynamics.',
    category: 'dynamic',
    family: 'Dynamic',
    emoji: '',
    featured: false,
    metrics: { fps: 60, bundleSize: '~0.0kb', complexity: 'Medium' },
    useCases: ['Creative interfaces', 'Special effects'],
    whySpecial: 'Highly experimental and fully GPU-accelerated.',
    bestFor: ['Creative interfaces', 'Special effects'],
    features: ['Creative interfaces', 'Special effects'],
    status: 'done',
  },
  {
    slug: 'squeeze',
    displayName: 'Squeeze',
    description: 'An amazing squeeze transition effect',
    longDescription: 'A highly experimental, beautifully choreographed transition featuring squeeze-inspired dynamics.',
    category: 'experimental',
    family: 'Experimental',
    emoji: '',
    featured: false,
    metrics: { fps: 60, bundleSize: '~0.0kb', complexity: 'Medium' },
    useCases: ['Creative interfaces', 'Special effects'],
    whySpecial: 'Highly experimental and fully GPU-accelerated.',
    bestFor: ['Creative interfaces', 'Special effects'],
    features: ['Creative interfaces', 'Special effects'],
    status: 'done',
  },
  {
    slug: 'ripple',
    displayName: 'Ripple',
    description: 'An amazing ripple transition effect',
    longDescription: 'A highly experimental, beautifully choreographed transition featuring ripple-inspired dynamics.',
    category: 'flow',
    family: 'Flow',
    emoji: '',
    featured: false,
    metrics: { fps: 60, bundleSize: '~0.0kb', complexity: 'Medium' },
    useCases: ['Creative interfaces', 'Special effects'],
    whySpecial: 'Highly experimental and fully GPU-accelerated.',
    bestFor: ['Creative interfaces', 'Special effects'],
    features: ['Creative interfaces', 'Special effects'],
    status: 'done',
  },
  {
    slug: 'vortex',
    displayName: 'Vortex',
    description: 'An amazing vortex transition effect',
    longDescription: 'A highly experimental, beautifully choreographed transition featuring vortex-inspired dynamics.',
    category: 'portal',
    family: 'Portal',
    emoji: '',
    featured: false,
    metrics: { fps: 60, bundleSize: '~0.0kb', complexity: 'Medium' },
    useCases: ['Creative interfaces', 'Special effects'],
    whySpecial: 'Highly experimental and fully GPU-accelerated.',
    bestFor: ['Creative interfaces', 'Special effects'],
    features: ['Creative interfaces', 'Special effects'],
    status: 'done',
  },
  {
    slug: 'tornado',
    displayName: 'Tornado',
    description: 'An amazing tornado transition effect',
    longDescription: 'A highly experimental, beautifully choreographed transition featuring tornado-inspired dynamics.',
    category: 'paper',
    family: 'Paper',
    emoji: '',
    featured: false,
    metrics: { fps: 60, bundleSize: '~0.0kb', complexity: 'Medium' },
    useCases: ['Creative interfaces', 'Special effects'],
    whySpecial: 'Highly experimental and fully GPU-accelerated.',
    bestFor: ['Creative interfaces', 'Special effects'],
    features: ['Creative interfaces', 'Special effects'],
    status: 'done',
  },
  {
    slug: 'swirl',
    displayName: 'Swirl',
    description: 'An amazing swirl transition effect',
    longDescription: 'A highly experimental, beautifully choreographed transition featuring swirl-inspired dynamics.',
    category: 'mask',
    family: 'Mask',
    emoji: '',
    featured: false,
    metrics: { fps: 60, bundleSize: '~0.0kb', complexity: 'Medium' },
    useCases: ['Creative interfaces', 'Special effects'],
    whySpecial: 'Highly experimental and fully GPU-accelerated.',
    bestFor: ['Creative interfaces', 'Special effects'],
    features: ['Creative interfaces', 'Special effects'],
    status: 'done',
  },
  {
    slug: 'twirl',
    displayName: 'Twirl',
    description: 'An amazing twirl transition effect',
    longDescription: 'A highly experimental, beautifully choreographed transition featuring twirl-inspired dynamics.',
    category: 'spatial',
    family: 'Spatial',
    emoji: '',
    featured: false,
    metrics: { fps: 60, bundleSize: '~0.0kb', complexity: 'Medium' },
    useCases: ['Creative interfaces', 'Special effects'],
    whySpecial: 'Highly experimental and fully GPU-accelerated.',
    bestFor: ['Creative interfaces', 'Special effects'],
    features: ['Creative interfaces', 'Special effects'],
    status: 'done',
  },
  {
    slug: 'kaleidoscope',
    displayName: 'Kaleidoscope',
    description: 'An amazing kaleidoscope transition effect',
    longDescription: 'A highly experimental, beautifully choreographed transition featuring kaleidoscope-inspired dynamics.',
    category: 'dynamic',
    family: 'Dynamic',
    emoji: '',
    featured: false,
    metrics: { fps: 60, bundleSize: '~0.0kb', complexity: 'Medium' },
    useCases: ['Creative interfaces', 'Special effects'],
    whySpecial: 'Highly experimental and fully GPU-accelerated.',
    bestFor: ['Creative interfaces', 'Special effects'],
    features: ['Creative interfaces', 'Special effects'],
    status: 'done',
  },
  {
    slug: 'mosaic',
    displayName: 'Mosaic',
    description: 'An amazing mosaic transition effect',
    longDescription: 'A highly experimental, beautifully choreographed transition featuring mosaic-inspired dynamics.',
    category: 'experimental',
    family: 'Experimental',
    emoji: '',
    featured: false,
    metrics: { fps: 60, bundleSize: '~0.0kb', complexity: 'Medium' },
    useCases: ['Creative interfaces', 'Special effects'],
    whySpecial: 'Highly experimental and fully GPU-accelerated.',
    bestFor: ['Creative interfaces', 'Special effects'],
    features: ['Creative interfaces', 'Special effects'],
    status: 'done',
  },
  {
    slug: 'glass',
    displayName: 'Glass',
    description: 'An amazing glass transition effect',
    longDescription: 'A highly experimental, beautifully choreographed transition featuring glass-inspired dynamics.',
    category: 'flow',
    family: 'Flow',
    emoji: '',
    featured: false,
    metrics: { fps: 60, bundleSize: '~0.0kb', complexity: 'Medium' },
    useCases: ['Creative interfaces', 'Special effects'],
    whySpecial: 'Highly experimental and fully GPU-accelerated.',
    bestFor: ['Creative interfaces', 'Special effects'],
    features: ['Creative interfaces', 'Special effects'],
    status: 'done',
  },
  {
    slug: 'mirror',
    displayName: 'Mirror',
    description: 'An amazing mirror transition effect',
    longDescription: 'A highly experimental, beautifully choreographed transition featuring mirror-inspired dynamics.',
    category: 'portal',
    family: 'Portal',
    emoji: '',
    featured: false,
    metrics: { fps: 60, bundleSize: '~0.0kb', complexity: 'Medium' },
    useCases: ['Creative interfaces', 'Special effects'],
    whySpecial: 'Highly experimental and fully GPU-accelerated.',
    bestFor: ['Creative interfaces', 'Special effects'],
    features: ['Creative interfaces', 'Special effects'],
    status: 'done',
  },
  {
    slug: 'prism',
    displayName: 'Prism',
    description: 'An amazing prism transition effect',
    longDescription: 'A highly experimental, beautifully choreographed transition featuring prism-inspired dynamics.',
    category: 'paper',
    family: 'Paper',
    emoji: '',
    featured: false,
    metrics: { fps: 60, bundleSize: '~0.0kb', complexity: 'Medium' },
    useCases: ['Creative interfaces', 'Special effects'],
    whySpecial: 'Highly experimental and fully GPU-accelerated.',
    bestFor: ['Creative interfaces', 'Special effects'],
    features: ['Creative interfaces', 'Special effects'],
    status: 'done',
  },
  {
    slug: 'neon',
    displayName: 'Neon',
    description: 'An amazing neon transition effect',
    longDescription: 'A highly experimental, beautifully choreographed transition featuring neon-inspired dynamics.',
    category: 'mask',
    family: 'Mask',
    emoji: '',
    featured: false,
    metrics: { fps: 60, bundleSize: '~0.0kb', complexity: 'Medium' },
    useCases: ['Creative interfaces', 'Special effects'],
    whySpecial: 'Highly experimental and fully GPU-accelerated.',
    bestFor: ['Creative interfaces', 'Special effects'],
    features: ['Creative interfaces', 'Special effects'],
    status: 'done',
  },
  {
    slug: 'laser',
    displayName: 'Laser',
    description: 'An amazing laser transition effect',
    longDescription: 'A highly experimental, beautifully choreographed transition featuring laser-inspired dynamics.',
    category: 'spatial',
    family: 'Spatial',
    emoji: '',
    featured: false,
    metrics: { fps: 60, bundleSize: '~0.0kb', complexity: 'Medium' },
    useCases: ['Creative interfaces', 'Special effects'],
    whySpecial: 'Highly experimental and fully GPU-accelerated.',
    bestFor: ['Creative interfaces', 'Special effects'],
    features: ['Creative interfaces', 'Special effects'],
    status: 'done',
  },
  {
    slug: 'hologram',
    displayName: 'Hologram',
    description: 'An amazing hologram transition effect',
    longDescription: 'A highly experimental, beautifully choreographed transition featuring hologram-inspired dynamics.',
    category: 'dynamic',
    family: 'Dynamic',
    emoji: '',
    featured: false,
    metrics: { fps: 60, bundleSize: '~0.0kb', complexity: 'Medium' },
    useCases: ['Creative interfaces', 'Special effects'],
    whySpecial: 'Highly experimental and fully GPU-accelerated.',
    bestFor: ['Creative interfaces', 'Special effects'],
    features: ['Creative interfaces', 'Special effects'],
    status: 'done',
  },
  {
    slug: 'ghost',
    displayName: 'Ghost Shift',
    description: 'An amazing ghost transition effect',
    longDescription: 'A highly experimental, beautifully choreographed transition featuring ghost-inspired dynamics.',
    category: 'experimental',
    family: 'Experimental',
    emoji: '',
    featured: true,
    metrics: { fps: 60, bundleSize: '~0.0kb', complexity: 'Medium' },
    useCases: ['Creative interfaces', 'Special effects'],
    whySpecial: 'Highly experimental and fully GPU-accelerated.',
    bestFor: ['Creative interfaces', 'Special effects'],
    features: ['Creative interfaces', 'Special effects'],
    status: 'done',
  },
  {
    slug: 'shadow',
    displayName: 'Shadow',
    description: 'An amazing shadow transition effect',
    longDescription: 'A highly experimental, beautifully choreographed transition featuring shadow-inspired dynamics.',
    category: 'flow',
    family: 'Flow',
    emoji: '',
    featured: false,
    metrics: { fps: 60, bundleSize: '~0.0kb', complexity: 'Medium' },
    useCases: ['Creative interfaces', 'Special effects'],
    whySpecial: 'Highly experimental and fully GPU-accelerated.',
    bestFor: ['Creative interfaces', 'Special effects'],
    features: ['Creative interfaces', 'Special effects'],
    status: 'done',
  },
  {
    slug: 'smoke',
    displayName: 'Smoke',
    description: 'An amazing smoke transition effect',
    longDescription: 'A highly experimental, beautifully choreographed transition featuring smoke-inspired dynamics.',
    category: 'portal',
    family: 'Portal',
    emoji: '',
    featured: false,
    metrics: { fps: 60, bundleSize: '~0.0kb', complexity: 'Medium' },
    useCases: ['Creative interfaces', 'Special effects'],
    whySpecial: 'Highly experimental and fully GPU-accelerated.',
    bestFor: ['Creative interfaces', 'Special effects'],
    features: ['Creative interfaces', 'Special effects'],
    status: 'done',
  },
  {
    slug: 'fire',
    displayName: 'Fire',
    description: 'An amazing fire transition effect',
    longDescription: 'A highly experimental, beautifully choreographed transition featuring fire-inspired dynamics.',
    category: 'paper',
    family: 'Paper',
    emoji: '',
    featured: false,
    metrics: { fps: 60, bundleSize: '~0.0kb', complexity: 'Medium' },
    useCases: ['Creative interfaces', 'Special effects'],
    whySpecial: 'Highly experimental and fully GPU-accelerated.',
    bestFor: ['Creative interfaces', 'Special effects'],
    features: ['Creative interfaces', 'Special effects'],
    status: 'done',
  },
  {
    slug: 'ice',
    displayName: 'Ice',
    description: 'An amazing ice transition effect',
    longDescription: 'A highly experimental, beautifully choreographed transition featuring ice-inspired dynamics.',
    category: 'mask',
    family: 'Mask',
    emoji: '',
    featured: false,
    metrics: { fps: 60, bundleSize: '~0.0kb', complexity: 'Medium' },
    useCases: ['Creative interfaces', 'Special effects'],
    whySpecial: 'Highly experimental and fully GPU-accelerated.',
    bestFor: ['Creative interfaces', 'Special effects'],
    features: ['Creative interfaces', 'Special effects'],
    status: 'done',
  },
  {
    slug: 'water',
    displayName: 'Water',
    description: 'An amazing water transition effect',
    longDescription: 'A highly experimental, beautifully choreographed transition featuring water-inspired dynamics.',
    category: 'spatial',
    family: 'Spatial',
    emoji: '',
    featured: false,
    metrics: { fps: 60, bundleSize: '~0.0kb', complexity: 'Medium' },
    useCases: ['Creative interfaces', 'Special effects'],
    whySpecial: 'Highly experimental and fully GPU-accelerated.',
    bestFor: ['Creative interfaces', 'Special effects'],
    features: ['Creative interfaces', 'Special effects'],
    status: 'done',
  },
  {
    slug: 'earth',
    displayName: 'Earth',
    description: 'An amazing earth transition effect',
    longDescription: 'A highly experimental, beautifully choreographed transition featuring earth-inspired dynamics.',
    category: 'dynamic',
    family: 'Dynamic',
    emoji: '',
    featured: false,
    metrics: { fps: 60, bundleSize: '~0.0kb', complexity: 'Medium' },
    useCases: ['Creative interfaces', 'Special effects'],
    whySpecial: 'Highly experimental and fully GPU-accelerated.',
    bestFor: ['Creative interfaces', 'Special effects'],
    features: ['Creative interfaces', 'Special effects'],
    status: 'done',
  },
  {
    slug: 'wind',
    displayName: 'Wind',
    description: 'An amazing wind transition effect',
    longDescription: 'A highly experimental, beautifully choreographed transition featuring wind-inspired dynamics.',
    category: 'experimental',
    family: 'Experimental',
    emoji: '',
    featured: false,
    metrics: { fps: 60, bundleSize: '~0.0kb', complexity: 'Medium' },
    useCases: ['Creative interfaces', 'Special effects'],
    whySpecial: 'Highly experimental and fully GPU-accelerated.',
    bestFor: ['Creative interfaces', 'Special effects'],
    features: ['Creative interfaces', 'Special effects'],
    status: 'done',
  },
  {
    slug: 'lightning',
    displayName: 'Lightning',
    description: 'An amazing lightning transition effect',
    longDescription: 'A highly experimental, beautifully choreographed transition featuring lightning-inspired dynamics.',
    category: 'flow',
    family: 'Flow',
    emoji: '',
    featured: false,
    metrics: { fps: 60, bundleSize: '~0.0kb', complexity: 'Medium' },
    useCases: ['Creative interfaces', 'Special effects'],
    whySpecial: 'Highly experimental and fully GPU-accelerated.',
    bestFor: ['Creative interfaces', 'Special effects'],
    features: ['Creative interfaces', 'Special effects'],
    status: 'done',
  },
  {
    slug: 'spark',
    displayName: 'Spark',
    description: 'An amazing spark transition effect',
    longDescription: 'A highly experimental, beautifully choreographed transition featuring spark-inspired dynamics.',
    category: 'portal',
    family: 'Portal',
    emoji: '',
    featured: false,
    metrics: { fps: 60, bundleSize: '~0.0kb', complexity: 'Medium' },
    useCases: ['Creative interfaces', 'Special effects'],
    whySpecial: 'Highly experimental and fully GPU-accelerated.',
    bestFor: ['Creative interfaces', 'Special effects'],
    features: ['Creative interfaces', 'Special effects'],
    status: 'done',
  },
  {
    slug: 'star',
    displayName: 'Star',
    description: 'An amazing star transition effect',
    longDescription: 'A highly experimental, beautifully choreographed transition featuring star-inspired dynamics.',
    category: 'paper',
    family: 'Paper',
    emoji: '',
    featured: false,
    metrics: { fps: 60, bundleSize: '~0.0kb', complexity: 'Medium' },
    useCases: ['Creative interfaces', 'Special effects'],
    whySpecial: 'Highly experimental and fully GPU-accelerated.',
    bestFor: ['Creative interfaces', 'Special effects'],
    features: ['Creative interfaces', 'Special effects'],
    status: 'done',
  },
  {
    slug: 'planet',
    displayName: 'Planet',
    description: 'An amazing planet transition effect',
    longDescription: 'A highly experimental, beautifully choreographed transition featuring planet-inspired dynamics.',
    category: 'mask',
    family: 'Mask',
    emoji: '',
    featured: false,
    metrics: { fps: 60, bundleSize: '~0.0kb', complexity: 'Medium' },
    useCases: ['Creative interfaces', 'Special effects'],
    whySpecial: 'Highly experimental and fully GPU-accelerated.',
    bestFor: ['Creative interfaces', 'Special effects'],
    features: ['Creative interfaces', 'Special effects'],
    status: 'done',
  },
  {
    slug: 'galaxy',
    displayName: 'Galaxy',
    description: 'An amazing galaxy transition effect',
    longDescription: 'A highly experimental, beautifully choreographed transition featuring galaxy-inspired dynamics.',
    category: 'spatial',
    family: 'Spatial',
    emoji: '',
    featured: false,
    metrics: { fps: 60, bundleSize: '~0.0kb', complexity: 'Medium' },
    useCases: ['Creative interfaces', 'Special effects'],
    whySpecial: 'Highly experimental and fully GPU-accelerated.',
    bestFor: ['Creative interfaces', 'Special effects'],
    features: ['Creative interfaces', 'Special effects'],
    status: 'done',
  },
  {
    slug: 'universe',
    displayName: 'Universe',
    description: 'An amazing universe transition effect',
    longDescription: 'A highly experimental, beautifully choreographed transition featuring universe-inspired dynamics.',
    category: 'dynamic',
    family: 'Dynamic',
    emoji: '',
    featured: false,
    metrics: { fps: 60, bundleSize: '~0.0kb', complexity: 'Medium' },
    useCases: ['Creative interfaces', 'Special effects'],
    whySpecial: 'Highly experimental and fully GPU-accelerated.',
    bestFor: ['Creative interfaces', 'Special effects'],
    features: ['Creative interfaces', 'Special effects'],
    status: 'done',
  },
  {
    slug: 'blackhole',
    displayName: 'Blackhole',
    description: 'An amazing blackhole transition effect',
    longDescription: 'A highly experimental, beautifully choreographed transition featuring blackhole-inspired dynamics.',
    category: 'experimental',
    family: 'Experimental',
    emoji: '',
    featured: false,
    metrics: { fps: 60, bundleSize: '~0.0kb', complexity: 'Medium' },
    useCases: ['Creative interfaces', 'Special effects'],
    whySpecial: 'Highly experimental and fully GPU-accelerated.',
    bestFor: ['Creative interfaces', 'Special effects'],
    features: ['Creative interfaces', 'Special effects'],
    status: 'done',
  },
  {
    slug: 'wormhole2',
    displayName: 'Wormhole2',
    description: 'An amazing wormhole2 transition effect',
    longDescription: 'A highly experimental, beautifully choreographed transition featuring wormhole2-inspired dynamics.',
    category: 'flow',
    family: 'Flow',
    emoji: '',
    featured: false,
    metrics: { fps: 60, bundleSize: '~0.0kb', complexity: 'Medium' },
    useCases: ['Creative interfaces', 'Special effects'],
    whySpecial: 'Highly experimental and fully GPU-accelerated.',
    bestFor: ['Creative interfaces', 'Special effects'],
    features: ['Creative interfaces', 'Special effects'],
    status: 'done',
  },
  {
    slug: 'time',
    displayName: 'Time',
    description: 'An amazing time transition effect',
    longDescription: 'A highly experimental, beautifully choreographed transition featuring time-inspired dynamics.',
    category: 'portal',
    family: 'Portal',
    emoji: '',
    featured: false,
    metrics: { fps: 60, bundleSize: '~0.0kb', complexity: 'Medium' },
    useCases: ['Creative interfaces', 'Special effects'],
    whySpecial: 'Highly experimental and fully GPU-accelerated.',
    bestFor: ['Creative interfaces', 'Special effects'],
    features: ['Creative interfaces', 'Special effects'],
    status: 'done',
  },
  {
    slug: 'space',
    displayName: 'Space',
    description: 'An amazing space transition effect',
    longDescription: 'A highly experimental, beautifully choreographed transition featuring space-inspired dynamics.',
    category: 'paper',
    family: 'Paper',
    emoji: '',
    featured: false,
    metrics: { fps: 60, bundleSize: '~0.0kb', complexity: 'Medium' },
    useCases: ['Creative interfaces', 'Special effects'],
    whySpecial: 'Highly experimental and fully GPU-accelerated.',
    bestFor: ['Creative interfaces', 'Special effects'],
    features: ['Creative interfaces', 'Special effects'],
    status: 'done',
  },
  {
    slug: 'dimension',
    displayName: 'Dimension',
    description: 'An amazing dimension transition effect',
    longDescription: 'A highly experimental, beautifully choreographed transition featuring dimension-inspired dynamics.',
    category: 'mask',
    family: 'Mask',
    emoji: '',
    featured: false,
    metrics: { fps: 60, bundleSize: '~0.0kb', complexity: 'Medium' },
    useCases: ['Creative interfaces', 'Special effects'],
    whySpecial: 'Highly experimental and fully GPU-accelerated.',
    bestFor: ['Creative interfaces', 'Special effects'],
    features: ['Creative interfaces', 'Special effects'],
    status: 'done',
  },
  {
    slug: 'reality',
    displayName: 'Reality',
    description: 'An amazing reality transition effect',
    longDescription: 'A highly experimental, beautifully choreographed transition featuring reality-inspired dynamics.',
    category: 'spatial',
    family: 'Spatial',
    emoji: '',
    featured: false,
    metrics: { fps: 60, bundleSize: '~0.0kb', complexity: 'Medium' },
    useCases: ['Creative interfaces', 'Special effects'],
    whySpecial: 'Highly experimental and fully GPU-accelerated.',
    bestFor: ['Creative interfaces', 'Special effects'],
    features: ['Creative interfaces', 'Special effects'],
    status: 'done',
  },
  {
    slug: 'dream',
    displayName: 'Dream',
    description: 'An amazing dream transition effect',
    longDescription: 'A highly experimental, beautifully choreographed transition featuring dream-inspired dynamics.',
    category: 'dynamic',
    family: 'Dynamic',
    emoji: '',
    featured: false,
    metrics: { fps: 60, bundleSize: '~0.0kb', complexity: 'Medium' },
    useCases: ['Creative interfaces', 'Special effects'],
    whySpecial: 'Highly experimental and fully GPU-accelerated.',
    bestFor: ['Creative interfaces', 'Special effects'],
    features: ['Creative interfaces', 'Special effects'],
    status: 'done',
  },
  {
    slug: 'nightmare',
    displayName: 'Nightmare',
    description: 'An amazing nightmare transition effect',
    longDescription: 'A highly experimental, beautifully choreographed transition featuring nightmare-inspired dynamics.',
    category: 'experimental',
    family: 'Experimental',
    emoji: '',
    featured: false,
    metrics: { fps: 60, bundleSize: '~0.0kb', complexity: 'Medium' },
    useCases: ['Creative interfaces', 'Special effects'],
    whySpecial: 'Highly experimental and fully GPU-accelerated.',
    bestFor: ['Creative interfaces', 'Special effects'],
    features: ['Creative interfaces', 'Special effects'],
    status: 'done',
  },
  {
    slug: 'illusion',
    displayName: 'Illusion',
    description: 'An amazing illusion transition effect',
    longDescription: 'A highly experimental, beautifully choreographed transition featuring illusion-inspired dynamics.',
    category: 'flow',
    family: 'Flow',
    emoji: '',
    featured: false,
    metrics: { fps: 60, bundleSize: '~0.0kb', complexity: 'Medium' },
    useCases: ['Creative interfaces', 'Special effects'],
    whySpecial: 'Highly experimental and fully GPU-accelerated.',
    bestFor: ['Creative interfaces', 'Special effects'],
    features: ['Creative interfaces', 'Special effects'],
    status: 'done',
  },
  {
    slug: 'crystal',
    displayName: 'Crystal',
    description: 'A crystalline structure grows and shatters to reveal the next page',
    longDescription: 'This transition is currently in development and will be available soon. It will feature a complex WebGL shader simulating organic crystal growth across the viewport before shattering.',
    category: 'experimental',
    family: 'Experimental',
    emoji: '',
    featured: false,
    metrics: { fps: 60, bundleSize: '~0.0kb', complexity: 'High' },
    useCases: ['Creative interfaces', 'Special effects'],
    whySpecial: 'Highly experimental and fully GPU-accelerated.',
    bestFor: ['Creative interfaces', 'Special effects'],
    features: ['Creative interfaces', 'Special effects'],
    status: 'done',
  },
  {
    slug: 'paint-drip',
    displayName: 'Paint Drip',
    description: 'Virtual paint drips down the screen, washing away the old page',
    longDescription: 'This transition is currently in development and will be available soon. It will simulate fluid dynamics for thick acrylic paint dripping from the top of the viewport.',
    category: 'mask',
    family: 'Mask',
    emoji: '',
    featured: false,
    metrics: { fps: 60, bundleSize: '~0.0kb', complexity: 'High' },
    useCases: ['Creative interfaces', 'Special effects'],
    whySpecial: 'Highly experimental and fully GPU-accelerated.',
    bestFor: ['Creative interfaces', 'Special effects'],
    features: ['Creative interfaces', 'Special effects'],
    status: 'done',
  },
  {
    slug: 'blueprint',
    displayName: 'Blueprint',
    description: 'The page turns into a glowing architectural blueprint wireframe',
    longDescription: 'This transition is currently in development and will be available soon. It will apply an edge-detection shader to render the DOM as a glowing cyan blueprint.',
    category: 'dynamic',
    family: 'Dynamic',
    emoji: '',
    featured: false,
    metrics: { fps: 60, bundleSize: '~0.0kb', complexity: 'Medium' },
    useCases: ['Creative interfaces', 'Special effects'],
    whySpecial: 'Highly experimental and fully GPU-accelerated.',
    bestFor: ['Creative interfaces', 'Special effects'],
    features: ['Creative interfaces', 'Special effects'],
    status: 'done',
  },
  {
    slug: 'lens-flare',
    displayName: 'Lens Flare',
    description: 'A cinematic anamorphic lens flare sweeps across blinding the camera',
    longDescription: 'This transition is currently in development and will be available soon. It will feature a J.J. Abrams style optical lens flare that acts as a wipe transition.',
    category: 'flow',
    family: 'Flow',
    emoji: '',
    featured: false,
    metrics: { fps: 60, bundleSize: '~0.0kb', complexity: 'Low' },
    useCases: ['Creative interfaces', 'Special effects'],
    whySpecial: 'Highly experimental and fully GPU-accelerated.',
    bestFor: ['Creative interfaces', 'Special effects'],
    features: ['Creative interfaces', 'Special effects'],
    status: 'done',
  },
  {
    slug: 'origami-crush',
    displayName: 'Origami Crush',
    description: 'The page crumples up into a tiny paper ball and is thrown away',
    longDescription: 'This transition is currently in development and will be available soon. It will use a physics engine and 3D mesh deformation to literally crumple the webpage.',
    category: 'paper',
    family: 'Paper',
    emoji: '🗞️',
    featured: false,
    metrics: { fps: 60, bundleSize: '~0.0kb', complexity: 'High' },
    useCases: ['Creative interfaces', 'Special effects'],
    whySpecial: 'Highly experimental and fully GPU-accelerated.',
    bestFor: ['Creative interfaces', 'Special effects'],
    features: ['Creative interfaces', 'Special effects'],
    status: 'done',
  }
];

// ---------------------------------------------------------------------------
// Derived Data Helpers
// ---------------------------------------------------------------------------

/** All unique family names, in display order */
export const FAMILIES = [...new Set(TRANSITION_CATALOG.map((t) => t.family))];

/** Map of family name → entries */
export function getTransitionsByFamily(): Record<string, TransitionCatalogEntry[]> {
  const result: Record<string, TransitionCatalogEntry[]> = {};
  for (const entry of TRANSITION_CATALOG) {
    if (!result[entry.family]) result[entry.family] = [];
    result[entry.family].push(entry);
  }
  return result;
}

/** Top 5 featured transitions for sidebar and marketing */
export const FEATURED_TRANSITIONS = TRANSITION_CATALOG.filter((t) => t.featured).slice(0, 5);

/** Lookup a single transition by slug */
export function getCatalogEntry(slug: string): TransitionCatalogEntry | undefined {
  return TRANSITION_CATALOG.find((t) => t.slug === slug);
}

/** All slugs for static param generation */
export function getAllTransitionSlugs(): string[] {
  return TRANSITION_CATALOG.map((t) => t.slug);
}

